// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVit760oSG0j7qJd4yE7e_UIaavO7mMQo',
    appId: '1:927740017245:web:3ec41fc0c6fe4dd9372bb4',
    messagingSenderId: '927740017245',
    projectId: 'coffe-shop-aeee0',
    authDomain: 'coffe-shop-aeee0.firebaseapp.com',
    storageBucket: 'coffe-shop-aeee0.appspot.com',
    measurementId: 'G-XY32JWMGQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN5kcRortfP_B8-0mjpZF_jC6sVSYoalA',
    appId: '1:927740017245:android:e190e3a92af04527372bb4',
    messagingSenderId: '927740017245',
    projectId: 'coffe-shop-aeee0',
    storageBucket: 'coffe-shop-aeee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8CzKt6nTkakYX-JOH-fgwZTb4rC2ow9Q',
    appId: '1:927740017245:ios:ef2f6fdb099441ce372bb4',
    messagingSenderId: '927740017245',
    projectId: 'coffe-shop-aeee0',
    storageBucket: 'coffe-shop-aeee0.appspot.com',
    iosBundleId: 'com.example.coffeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8CzKt6nTkakYX-JOH-fgwZTb4rC2ow9Q',
    appId: '1:927740017245:ios:ef2f6fdb099441ce372bb4',
    messagingSenderId: '927740017245',
    projectId: 'coffe-shop-aeee0',
    storageBucket: 'coffe-shop-aeee0.appspot.com',
    iosBundleId: 'com.example.coffeShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVit760oSG0j7qJd4yE7e_UIaavO7mMQo',
    appId: '1:927740017245:web:31aae79ae249474f372bb4',
    messagingSenderId: '927740017245',
    projectId: 'coffe-shop-aeee0',
    authDomain: 'coffe-shop-aeee0.firebaseapp.com',
    storageBucket: 'coffe-shop-aeee0.appspot.com',
    measurementId: 'G-HKXR79GQW3',
  );
}
